name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Approvals on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install fzf
      run: sudo apt install -y fzf
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2
    - name: Run shellcheck tests
      run: shellcheck fuzzycd setup
    - name: Run approval tests
      run: test/approve

  test_mac:
    name: Approvals on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install fzf
      run: brew install fzf
    - name: Run approval tests
      run: test/approve

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run setup approval tests
      run: test/approve_setup

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run setup approval tests
      run: test/approve_setup

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run shellcheck tests
      run: shellcheck setup fuzzycd && echo PASS
